FROM apache/spark:4.1.1-python3

USER root

# Utils 
RUN apt-get update && apt-get install -y \
    curl \
    procps \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH

# Hadoop AWS / S3A
ENV HADOOP_AWS_VERSION=3.3.6
ENV AWS_SDK_VERSION=1.12.509

RUN curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
    -o $SPARK_HOME/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
 && curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
    -o $SPARK_HOME/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar

# COPY SPARK DEFAULT CONFIG
COPY conf/spark-defaults.conf $SPARK_HOME/conf/spark-defaults.conf
RUN chmod 644 $SPARK_HOME/conf/spark-defaults.conf

USER spark
