# Stage 1: Build Stage
FROM golang:alpine AS builder

# Cài đặt các gói cần thiết
RUN apk add --no-cache git
RUN go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /app

COPY . .

# 1. Xóa file cũ
RUN rm -f go.mod go.sum

# 2. Khởi tạo module
RUN go mod init minio-admin-api

# 3. Authen with JWT
RUN go get github.com/golang-jwt/jwt/v5


# === SỬA QUAN TRỌNG TẠI ĐÂY ===
# Ép buộc lấy thư viện swag bản mới nhất (để khớp với tool CLI)
RUN go get github.com/swaggo/swag@latest
RUN go get github.com/swaggo/files@latest
RUN go get github.com/swaggo/gin-swagger@latest

# Sau đó mới chạy tidy để dọn dẹp các thư viện khác
RUN go mod tidy
# ==============================

# 3. Sinh Docs
RUN swag init

# 4. Build
RUN CGO_ENABLED=0 GOOS=linux go build -o minio-api main.go

# Stage 2: Run Stage (Giữ nguyên)
FROM alpine:latest
WORKDIR /root/
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/minio-api .
EXPOSE 8080
CMD ["./minio-api"]