FROM apache/spark:3.5.8-python3

USER root

# Utils 
RUN apt-get update && apt-get install -y \
    curl \
    procps \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH

# Hadoop AWS / S3A
ENV HADOOP_AWS_VERSION=3.3.4
ENV AWS_SDK_VERSION=1.12.262

# Download and install common Jars (Postgres, Neo4j) - CHECK COMPATIBILITY
# Using Postgres JDBC 42.7.2
RUN curl -L https://jdbc.postgresql.org/download/postgresql-42.7.2.jar \
    -o $SPARK_HOME/jars/postgresql-42.7.2.jar

# Neo4j Connector for Spark (Spark 3.5 uses Scala 2.12 by default in official images usually, checking tag...)
# Official images often stick to Scala 2.12 for Spark 3.x.
# Using 5.4.0_for_spark_3 (Scala 2.12)
RUN curl -L https://repo1.maven.org/maven2/org/neo4j/neo4j-connector-apache-spark_2.12/5.4.0_for_spark_3/neo4j-connector-apache-spark_2.12-5.4.0_for_spark_3.jar \
    -o $SPARK_HOME/jars/neo4j-connector-apache-spark_2.12-5.4.0_for_spark_3.jar

RUN curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
    -o $SPARK_HOME/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
 && curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
    -o $SPARK_HOME/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar

# Install Python deps
COPY _config/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# COPY SPARK DEFAULT CONFIG
COPY _config/spark-defaults.conf $SPARK_HOME/conf/spark-defaults.conf
RUN chmod 644 $SPARK_HOME/conf/spark-defaults.conf

USER spark
