# =========================
# Spark Master
# =========================
spark.master                     spark://spark-master:7077

# =========================
# MinIO / S3A
# =========================
spark.hadoop.fs.s3a.endpoint                     http://minio:9000
spark.hadoop.fs.s3a.access.key                   minioadmin
spark.hadoop.fs.s3a.secret.key                   minioadmin
spark.hadoop.fs.s3a.path.style.access            true
spark.hadoop.fs.s3a.connection.ssl.enabled       false
spark.hadoop.fs.s3a.impl                         org.apache.hadoop.fs.s3a.S3AFileSystem
# USING AWS SDK v1
spark.hadoop.fs.s3a.aws.credentials.provider     org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

# TIMEOUT ONLY NUMBERIC
spark.hadoop.fs.s3a.connection.timeout           60000
spark.hadoop.fs.s3a.connection.establish.timeout 60000
spark.hadoop.fs.s3a.retry.interval               5000
spark.hadoop.fs.s3a.threads.keepalivetime        60000
spark.hadoop.fs.s3a.multipart.purge.age          86400000


# =========================
# Stability
# =========================
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.sql.parquet.compression.codec snappy
